Repository hmcts/chart-library, pull requests merged in 2022-03, with the labels that each got.

#51 Add certificate support in helm
  README.md
  ci-values-lang.yaml
  ci-values.yaml
  library/templates/v2/_secretproviderclass-tests.tpl
  library/templates/v2/_secretproviderclass.tpl
  tests/results/secretproviderclass-tests.yaml
  tests/results/secretproviderclass.yaml
  tests/v2/secretproviderclass.yaml
Labels: enhancement

#52 DTSPO-6480 - Oauth annotations
  ci-values-lang.yaml
  ci-values.yaml
  library/templates/v2/_ingress.tpl
Labels: enhancement

#53 Don't chomp whitespace after document separator
  library/templates/v2/_service.tpl
Labels: bug

#55 Fix typo
  README.md
Labels: documentation
